#!/usr/bin/env python2

import sys
import os
import pulsectl
import time
import traceback
import threading
import gtk
import hband_tools.gui as gui
try:
	import better_exchook
except ImportError:
	pass
else:
	better_exchook.install()


APPNAME = 'paosd'


def listen_pulse_events():
	while State['run']:
		if State['pulse_listener'] is None: State['pulse_listener'] = pulsectl.Pulse(APPNAME)
		State['pulse_listener'].event_mask_set('sink')
		State['pulse_listener'].event_callback_set(on_pulse_event)
		try:
			State['pulse_listener'].event_listen(timeout=None)
			time.sleep(1)
		except pulsectl.PulseDisconnected:
			State['pulse_listener'] = None
		except:
			pass

def on_pulse_event(event):
	for sink in pulseproxy.sink_list():
		sink_desc = sink.description
		port_desc = sink.port_active.description
		muted = sink.mute
		volume = sink.volume.value_flat * 100
		volume = int(volume)
		display_volume(sink, sink_desc, port_desc, muted, volume)

InfoDisplayedPerDevice = {}

def display_volume(pa_sink, device, device_port, muted, volume):
	key = (device, device_port)
	info = (muted, volume)
	if InfoDisplayedPerDevice.get(key, (None, None)) != info:
		gtk.threads_enter()
		main_win.current_pa_sink = pa_sink
		main_win.update(device + " - " + device_port, muted, volume)
		# TODO timer to hide
		gtk.threads_leave()
		InfoDisplayedPerDevice[key] = info

class VolumeWindow(gui.Window):
	def __init__(self):
		self.current_pa_sink = None
		
		super(VolumeWindow, self).__init__({'name': 'window.main', 'gtk-args': [gtk.WINDOW_TOPLEVEL]})
		self.set_decorated(False)
		self.set_skip_taskbar_hint(True)
		self.set_skip_pager_hint(True)
		self.set_keep_above(True)
		
		frame = gtk.Frame()
		frame.set_shadow_type(gtk.SHADOW_OUT)
		box = gtk.VBox(homogeneous=False, spacing=0)
		hbox = gtk.HBox(homogeneous=False, spacing=5)
		
		self.scale = gtk.HScale(gtk.Adjustment(0.0, 0.0, 100.0, 1.0, 10.0, 0.0))
		self.scale.set_update_policy(gtk.UPDATE_CONTINUOUS)
		self.scale.set_draw_value(False)
		self.scale.set_inverted(False)
		self.scale.set_size_request(120, 0)
		#self.scale.connect('value-changed', scale_adjusted)
		
		self.icon = gtk.ToolButton()
		self.icon.connect('clicked', toggle_mute_current_device_port)
		self.voltext = gtk.Label()
		self.label = gtk.Label()
		self.label.set_alignment(0, 0.5)
		
		box.pack_start(hbox, expand=False, fill=False, padding=0)
		hbox.pack_start(self.icon, expand=False, fill=False, padding=0)
		hbox.pack_start(self.voltext, expand=False, fill=False, padding=0)
		hbox.pack_start(self.scale, expand=True, fill=True, padding=0)
		box.pack_start(self.label, expand=True, fill=True, padding=0)
		frame.add(box)
		self.add(frame)
		self.show_all()
	
	def update(self, label, muted, volume):
		self.scale.set_value(volume)
		self.update_icon(muted)
		self.voltext.set_text('%d%%' % volume)
		self.label.set_text(label)
		self.show_all()
	
	def update_icon(self, muted):
		volume = self.scale.get_value()
		if muted or volume <= 0: icon_variant = 'mute'
		elif volume < 33:        icon_variant = 'min'
		elif volume < 66:        icon_variant = 'med'
		else:                    icon_variant = 'max'
		self.icon.set_icon_name('stock_volume-%s' % icon_variant)

class PulseProxy(object):
	def __init__(self):
		self.pa = pulsectl.Pulse(APPNAME)
	def connect(self):
		if not self.pa.connected:
			self.pa.connect()
	def toggle_mute(self, sink):
		self.connect()
		State['pulse_listener'].event_listen_stop()
		desired_state = not sink.mute
		self.pa.mute(sink, desired_state)
		return desired_state
	def mute(self, sink):
		self.connect()
		State['pulse_listener'].event_listen_stop()
		self.pa.mute(sink, True)
	def unmute(self, sink):
		self.connect()
		State['pulse_listener'].event_listen_stop()
		self.pa.mute(sink, False)
	def sink_list(self):
		self.connect()
		return self.pa.sink_list()

def toggle_mute_current_device_port(mute_button):
	if main_win.current_pa_sink is not None:
		muted = pulseproxy.toggle_mute(main_win.current_pa_sink)
		main_win.update_icon(muted)



State = {
	'run': True,
	'pulse_listener': None,
}


pulseproxy = PulseProxy()

gtk.gdk.threads_init()
pulse_listen_thr = threading.Thread(target=listen_pulse_events, name='Pulse listener')
pulse_listen_thr.setDaemon(True)
pulse_listen_thr.start()

main_win = VolumeWindow()
main_win.hide()
try:
	gtk.main()
except KeyboardInterrupt:
	pass

State['run'] = False
if State['pulse_listener'] is not None: State['pulse_listener'].disconnect()
pulse_listen_thr.join()
