#!/usr/bin/env python3

import os
import pulsectl
import time
import traceback


def listen_pulse_events():
	while True:
		try:
			while True:
				pulse_listener.event_listen(timeout=86400)
				time.sleep(1)
		except pulsectl.PulseDisconnected:
			traceback.print_exc()


def default_pulseSink():
	default = pulse_blocking.server_info().default_sink_name
	for sink in pulse_blocking.sink_list():
		if sink.name == default:
			return sink
	return pulse_blocking.sink_list()[0]


def pulse_event(event):
	for sink in pulse_blocking.sink_list():
		sink_desc = sink.description
		port_desc = sink.port_active.description
		muted = sink.mute
		volume = sink.volume.value_flat * 100
		volume = int(volume)
		label = f"{sink_desc} - {port_desc}"
		osm = f"{label} - {'MUTED ' if muted else ''}({int(volume)}%)"
		print(osm)
		display_volume(sink_desc, volume, osm)


def osd_volume(volume, label='volume'):
	label_esc = label.replace(')', '\\)')
	osd(f"bars({label_esc},{volume})")


def osd(command):
	with open(f"/tmp/osdsh.{os.getuid()}", 'w') as fh:
		fh.write(command)


InfoDisplayedPerDevice = {}

def display_volume(device, volume, osm):
	info = (volume, osm)
	if InfoDisplayedPerDevice.get(device, (None, None)) != info:
		osd_volume(volume, osm)
		InfoDisplayedPerDevice[device] = info


pulse_listener = pulsectl.Pulse('paosd')
pulse_blocking = pulsectl.Pulse('paosd')

pulse_listener.event_mask_set('sink')
pulse_listener.event_callback_set(pulse_event)
listen_pulse_events()
